# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7fe7717b599914d6875bd71241b1c700"
name = "Store Locator GBP"
handle = "store-locator-gbp"
application_url = "https://store-locator-gbp--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "asv-gadget.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://store-locator-gbp--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
